#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

var=0
while [ $var -ne 10 ]
do 
    if [ $var -eq 8 ]
        then echo "Hi"
    else
       echo "Best School" 
    fi
    var=$((var + 1))
done