#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

var=0
while [ $var -ne 10 ]
do 
    var=$((var + 1))
    if [ $var -eq 4 ]
        then echo "bad luck"
    elif [ $var -eq 8 ]
        then echo "good luck"
    else
        echo "Best School"
    fi
done