#!/usr/bin/env bash
# Display numbers from 1 to 10

var=1
while [ $var -ne 21 ]
do 
    echo "$var"

    case $var in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    var=$((var + 1))
done