#!/usr/bin/env bash
#Display hours from 0 to 12 and minutes from 0 to 59

hours=0

while [ $hours -ne 13 ]
do 
    echo "Hour: $hours"
    min=0

    while [ $min -ne 60 ]
    do
        echo "$min"
        min=$((min + 1))
    done

    hours=$((hours + 1))
done