#!/usr/bin/env bash
# Display numbers from 1 to 10

hours=0
min=0
while [ $hours -ne 25 ]
do 
    echo "Hour: $hours"
    min=0

    while [ $min -ne 61 ]
    do
        echo "$min"
        min=$((min + 1))
    done

    hours=$((hours + 1))
done