#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for file in $(ls)
do
    # Extract the part after the first dash using cut
    name_part=$(echo "$file" | cut -d'-' -f2-)
    echo "$name_part"
done